### ISSUE TITLE
Network Hashrate and difficulty

### ISSUE THREAD

**Issue by MiningCryptoLive** [etclabscore/core-pool-interface#159]
I am working on building the frontend and everything seems to work except Network hashrate and difficulty show Nan undefinedH
Any updates? Everything for the frontend shows but now none of the stats work. No block height, hashrate epoch

**Comment by cristianvsl** [comment]
Same issue. It shows for a while and at first refresh it shows NaN

**Comment by MiningCryptoLive** [comment]
I fixed the network hashrate & network difficulty issues.

line 56 of store/index.js needs to be changed to 
state.networkHashrate = info.difficulty / TARGET_TIME
line 57 needs to be changed to 
state.difficulty = info.difficulty

**Comment by MiningCryptoLive** [comment]
> Same issue. It shows for a while and at first refresh it shows NaN

See my post on how to fix the issue
